blog/urls.py
from django.urls import path

from blog.views import BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blogpost/view/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blogpost/<int:pk>/edit/', BlogPostUpdateView.as_view(), name='blogpost_edit'),
    path('blogpost/<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
    path('blogpost/create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blogpost/view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.views import MailingSettingsListView, MailingSettingsUpdateView, MailingSettingsDeleteView, \
    MailingSettingsCreateView, MailingSettingsDetailView, HomeView, MessageCreateView, UserListView, \
    MailingListManagerView, MessageListView, MessageDetailsView, MessageDeleteView, MessageUpdateView, ClientCreateView, \
    ClientDetailsView, ClientDeleteView, ClientUpdateView, ClientListView

app_name = 'mailing'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('mailing/settings/view/', MailingSettingsListView.as_view(), name='mailing_list'),
    path('mailing/settings/<int:pk>/edit/', MailingSettingsUpdateView.as_view(), name='mailing_settings_update'),
    path('mailing/settings/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='mailing_settings_delete'),
    path('mailing/settings/create/', MailingSettingsCreateView.as_view(), name='mailing_settings_create'),
    path('mailing/settings/<int:pk>/', MailingSettingsDetailView.as_view(), name='mailing_details'),
    path('mailing/message/view/', MessageCreateView.as_view(), name='message_create'),
    path('users/', UserListView.as_view(), name='user_list'),
    path('mailing/settings/view/manage/', MailingListManagerView.as_view(), name='mailing_list_manager'),
    path('mailing/message/view/list/', MessageListView.as_view(), name='message_list'),
    path('mailing/message/view/<int:pk>/', MessageDetailsView.as_view(), name='message_details'),
    path('mailing/message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing/message/<int:pk>/edit/', MessageUpdateView.as_view(), name='message_update'),
    path('mailing/client/view/', ClientCreateView.as_view(), name='client_create'),
    path('mailing/client/view/list/', ClientListView.as_view(), name='client_list'),
    path('mailing/client/view/<int:pk>/', ClientDetailsView.as_view(), name='client_details'),
    path('mailing/client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing/client/<int:pk>/edit/', ClientUpdateView.as_view(), name='client_update'),

]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, ConfirmEmailView, ConfirmationSuccessView, \
    ConfirmationErrorView, CreationErrorView, ChangePasswordView, GenerateAndSendPasswordView, LoginUserView

app_name = UsersConfig.name
urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login_in'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users/verify_email/', VerifyEmailView.as_view(), name='verification_email'),
    path('confirm_email/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('error_create/', CreationErrorView.as_view(), name='error_create'),
    path('confirmation_success/', ConfirmationSuccessView.as_view(), name='confirmation_success'),
    path('confirmation_error/', ConfirmationErrorView.as_view(), name='confirmation_error'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('generate_send_password/', GenerateAndSendPasswordView.as_view(), name='generate_send_password'),

]

mailing/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class MailingMessage(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема')
    message_content = models.TextField(verbose_name='Содержание')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='Владелец')
    objects = models.Manager()

    def __str__(self):
        return f'{self.subject}:\n {self.message_content}'

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'


class Client(models.Model):
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    email = models.EmailField(max_length=100, verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    objects = models.Manager()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='владелец')

    def __str__(self):
        return f'{self.full_name}: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingSettings(models.Model):
    objects = models.Manager()
    DELIVERY_FREQUENCY_CHOICES = (
        ('daily', 'Ежедневная'),
        ('weekly', 'Еженедельная'),
        ('monthly', 'Ежемесячная'),
    )
    DELIVERY_STATUS_CHOICES = (
        ('completed', 'Завершена'),
        ('created', 'Создана'),
        ('running', 'Запущена'),
    )
    start_time = models.DateTimeField(blank=True)
    end_time = models.DateTimeField(default=None)
    frequency = models.CharField(max_length=20, choices=DELIVERY_FREQUENCY_CHOICES, default='weekly')
    status = models.CharField(max_length=20, choices=DELIVERY_STATUS_CHOICES, default='created')
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE,
                                verbose_name='Сообщение для рассылки', **NULLABLE)
    client = models.ManyToManyField(Client,
                                    verbose_name='Клиент рассылки')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='владелец')
    is_active = models.BooleanField(default=False, verbose_name='Статус активности')

    def __str__(self):
        return f"{self.frequency} рассылка в {self.start_time} {self.client}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('can_set_mailing_activity', 'Can change mailing activity'),
        ]


class EmailLog(models.Model):
    STATUSES = (
        ('STATUS_OK', 'Успешно'),
        ('STATUS_FAILED', 'Ошибка'),
    )
    datetime_attempt = models.DateTimeField(auto_now_add=True, verbose_name='Последняя попытка')
    status = models.CharField(choices=STATUSES, max_length=20, default='STATUS_OK', verbose_name='Статус')
    client = models.ManyToManyField(Client, verbose_name='Клиент')
    settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='Настройки', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'Логи рассылки - {self.status}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'

mailing/forms.py
from django import forms

from mailing.models import MailingSettings, MailingMessage, Client


class MailingSettingsCreateForm(forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = '__all__'
        widgets = {
            'start_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'end_time': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'frequency': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'message': forms.Select(attrs={'class': 'form-control'}),
            'owner': forms.Select(attrs={'class': 'form-control'}),
        }

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.owner = self.cleaned_data['owner']
        if commit:
            instance.save()
        return instance


class MailingMessageCreateForm(forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = '__all__'

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.owner = self.cleaned_data['owner']
        if commit:
            instance.save()
        return instance


class ClientCreateForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.owner = self.cleaned_data['owner']
        if commit:
            instance.save()
        return instance

mailing/templates/mailing/base.html
{% load static %}

<head>
    <title>Здарова</title>
    <link href="{% static 'css/doc.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<div class="container">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">
                {% if user.is_authenticated %}
                <a class="text-muted" href="{% url 'mailing:mailing_list' %}">Количество рассылок: {{ total_mailings }}</a><br>
                <a class="text-muted" href="#">Количество активных рассылок: {{ active_mailings }}</a><br>
                <a class="text-muted" href="{% url 'mailing:client_list' %}">Количество клиентов: {{ unique_clients }}</a>
                {% else %}
                {% endif %}
            </div>
            <div class="col-4 text-center">
                <a class="blog-header-logo text-dark" href="{% url 'mailing:home' %}">Огромный</a>
            </div>
        </div>
    </header>

    <div class="nav-scroller py-1 mb-2">
        {% if user.is_authenticated %}
        <nav class="nav d-flex justify-content-between">
            <a class="p-2 text-muted" href="{% url 'users:logout' %}">Выйти</a>
            <a class="p-2 text-muted" href="{% url 'mailing:mailing_settings_create' %}">Создать
                рассылку</a>
            <a class="p-2 text-muted" href="{% url 'mailing:message_create' %}">Создать
                сообщение</a>
            <a class="p-2 text-muted" href="{% url 'mailing:client_create' %}">Создать
                клиента</a>
            {% if user.is_staff or user.is_superuser %}
            <a class="p-2 text-muted" href="{% url 'mailing:mailing_list_manager' %}">Список рассылок</a>
            <a class="p-2 text-muted" href="{% url 'mailing:message_list' %}">Список сообщений</a>
            <a class="p-2 text-muted" href="{% url 'mailing:client_list' %}">Список клиентов</a>
            {% else %}
            <a class="p-2 text-muted" href="{% url 'mailing:mailing_list' %}">Список рассылок</a>
            <a class="p-2 text-muted" href="{% url 'mailing:message_list' %}">Список сообщений</a>
            <a class="p-2 text-muted" href="{% url 'mailing:client_list' %}">Список клиентов</a>
            {% endif %}
            <a class="p-2 text-muted" href="{% url 'mailing:user_list' %}">Список пользователей</a>
            <a class="p-2 text-muted" href="{% url 'users:profile' %}">Профиль</a>
            {% else %}
            <a class="p-2 text-muted" href="{% url 'users:login_in' %}">Войти</a>
            <a class="p-2 text-muted" href="{% url 'users:register' %}">Регистрация</a>
            {% endif %}
        </nav>
    </div>
</div>
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-4 font-italic">Напиши свой пост!</h1>
        <p class="lead my-3">Стань популярным инфлюенсером!</p>
        <p class="lead mb-0"><a href="{% url 'blog:blogpost_create' %}" class="text-white font-weight-bold">Стать
            крутым</a></p>
        <p class="lead mb-0"><a href="{% url 'blog:blogpost_list' %}" class="text-white font-weight-bold">Посмотреть на
            других крутышек</a></p>
    </div>


</div>
{% block content %}
{% endblock %}


<footer class="blog-footer d-flex justify-content-center align-items-center w-100 flex-column">
    <p>сделано с душой</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
<script>
    Holder.addTheme('thumb', {
      bg: '#55595c',
      fg: '#eceeef',
      text: 'Thumbnail'
    });
</script>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы уверены, что хотите удалить данного клиента?</p>
                            <button type="submit" class="btn btn-dark">Подтвердить</button>
                            <a href="{% url 'mailing:client_list' %}" class="btn btn-info">Отменить</a>

                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

mailing/templates/mailing/client_create.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                Создать сообщение
            </h3>

            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit">
                            Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/client_details.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{ clients.full_name }}</h3>
            <p>{{ clients.email }}</p>
            <p>{{ clients.comment }}</p>
            <div class="dropdown">
                <button class="btn btn-block btn-primary dropdown-toggle" type="button" id="addDropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Редактирование
                </button>
                <div class="dropdown-menu" aria-labelledby="addDropdown">
                    <a href="{% url 'mailing:client_delete' clients.id %}"
                       class="btn btn-dark">Удалить</a>
                    <a href="{% url 'mailing:client_update' clients.id %}"
                       class="btn btn-info">Редактировать</a>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<h1>Список клиентов</h1>
{% for client in clients %}
{% include 'mailing/includes/inc_mailing_clients.html' %}
{% endfor %}<br>
{% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<div class="row mb-4 justify-content-center"> <!-- Добавлен класс justify-content-center -->
    <div class="col-md-4">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-primary">{{ top_article.views_count }} просмотров</strong>
                <h3 class="mb-0">
                    <a class a="text-dark" href="#">{{ top_article.title }}</a>
                </h3>
                <div class="mb-1 text-muted">{{ top_article.created_date }}</div>
                <p class="card-text mb-auto">{{ top_article.content|truncatewords:15 }}</p>
                <a href="{% url 'blog:blogpost_view' top_article.pk %}">Читать далее...</a>
            </div>
            <img src="{{ top_article.preview|mymedia }}" alt="Изображение" class="card-img-right img-fluid"
                 style="width: 400; height: 200px;"><br>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card flex-md-row mb-4 box-shadow h-md-250">
            <div class="card-body d-flex flex-column align-items-start">
                <strong class="d-inline-block mb-2 text-primary">{{ latest_article.views_count }} просмотров</strong>
                <h3 class="mb-0">
                    <a class a="text-dark" href="#">{{ latest_article.title }}</a>
                </h3>
                <div class="mb-1 text-muted">{{ latest_article.created_date }}</div>
                <p class="card-text mb-auto">{{ latest_article.content|truncatewords:15 }}</p>
                <a href="{% url 'blog:blogpost_view' latest_article.pk %}">Читать далее...</a>
            </div>
            <img src="{{ latest_article.preview|mymedia }}" alt="Изображение" class="card-img-right img-fluid"
                 style="width: 300; height: 200px;"><br>
        </div>
    </div>
</div>


<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                Ждули
            </h3>
            {% for article in random_articles %}
            <div class="blog-post">
                <h2 class="blog-post-title">{{ article.title }}</h2>
                {% for category in article.category.all %}
                <a href="#">{{ category.name }}</a>
                {% endfor %}
                <p class="blog-post-meta">{{ article.created_date }} <a href="#">{{ article.owner }}</a></p>
                <p>{{ article.content }}</p>
                <img src="{{ article.preview|mymedia }}" alt="Изображение" class="card-img-right img-fluid"
                     style="max-width: 600px;"><br>
                <div class="card-footer">
                </div><!-- /.blog-post -->
                {% endfor %}
            </div>
        </div>
    </div>
</main>

<nav class="blog-pagination">
    <a class="btn btn-outline-primary" href="#">Older</a>
    <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
</nav>


{% endblock %}

mailing/templates/mailing/mailing_details.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ mailing.get_frequency_display }} рассылка </h2>
            <h6 class="card-title">Статус: {{ mailing.get_status_display }}</h6>
            <h4>Клиенты рассылки:</h4>
                {% for client in mailing.client.all %}
            <div>
                <h6> Имя: {{ client.full_name }}</h6>
                <p>Почта: {{ client.email }}</p>
                <p>Комментарий: {{ client.comment }}</p>
            </div>
            {% empty %}
            <p>Нет связанных клиентов.</p>
            {% endfor %}
            <h4>Время рассылки:</h4>
            <p>{{ mailing.start_time }} - {{ mailing.end_time }}</p>
            <h4>Сообщение рассылки:</h4>
            <p>{{ mailing.message.subject }}: {{ mailing.message.message_content }}</p>


            <div class="dropdown">
                <button class="btn btn-block btn-primary dropdown-toggle" type="button" id="addDropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Редактирование
                </button>
                <div class="dropdown-menu" aria-labelledby="addDropdown">
                    <a href="{% url 'mailing:mailing_settings_delete' mailing.id %}"
                       class="btn btn-dark">Удалить</a>
                    <a href="{% url 'mailing:mailing_settings_update' mailing.id %}"
                       class="btn btn-info">Редактировать</a>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

mailing/templates/mailing/mailing_list_manager.html
{% extends 'mailing/base.html' %}

{% block content %}
<h1>Список рассылок</h1>
{% for mailing_client in mailing_clients %}
<div>
    <h3 class="card-title">{{ mailing_client.get_frequency_display }} рассылка </h3>
    <p>{{ mailing_client.start_time }} - {{ mailing_client.end_time }}</p>
    <h4>Клиенты рассылки</h4>
    {% for client in mailing_client.client.all %}
    <div>
        <h6>{{ client }}</h6>

    </div>
    {% endfor %}


    <h4>Сообщение рассылки:</h4>
    <p>{{ mailing_client.message }}</p>
    <h5>{{ mailing_client.get_status_display }}</h5>
    <form method="post" action="{% url 'mailing:mailing_list_manager' %}">
        {% csrf_token %}
        <input type="hidden" name="mailing_id" value="{{ mailing_client.id }}">
        <button class="btn {% if mailing_client.is_active == False %}btn-primary{% else %}btn-secondary{% endif %}"
                type="submit">
            {% if mailing_client.is_active == True %}
            Отключить
            {% else %}
            Включить
            {% endif %}
        </button>
    </form>

</div>
{% endfor %}
{% if not mailing_client %}
<p>Клиентов нет.</p>
{% endif %}
{% endblock %}

mailing/templates/mailing/mailing_settings_create.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                Настройки рассылки
            </h3>

            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit">
                            Сохранить
                        </button>
                    </form>
                </div>
            </div>


{% endblock %}

mailing/templates/mailing/mailingclient_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы уверены, что хотите удалить данную рассылку?</p>
                            <button type="submit" class="btn btn-dark">Подтвердить</button>
                            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-info">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Вы уверены, что хотите удалить данное сообщение?</p>
                            <button type="submit" class="btn btn-dark">Подтвердить</button>
                            <a href="{% url 'mailing:message_list' %}" class="btn btn-info">Отменить</a>

                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

mailing/templates/mailing/message_create.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8 blog-main">
            <h3 class="pb-3 mb-4 font-italic border-bottom">
                Настройки рассылки
            </h3>

            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit">
                            Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/message_details.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">{{ mailing_messages.subject }}</h3>
            <p>{{ mailing_messages.message_content }}</p>
            <p>{{ mailing_messages.owner }}</p>
            <div class="dropdown">
                <button class="btn btn-block btn-primary dropdown-toggle" type="button" id="addDropdown"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Редактирование
                </button>
                <div class="dropdown-menu" aria-labelledby="addDropdown">
                    <a href="{% url 'mailing:message_delete' mailing_messages.id %}"
                       class="btn btn-dark">Удалить</a>
                    <a href="{% url 'mailing:message_update' mailing_messages.id %}"
                       class="btn btn-info">Редактировать</a>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}


<h1>Список пользователей</h1>
{% for user in user_list %}
  <div>
    <span>{{ user.email }}</span>
    <form method="post" action="{% url 'mailing:user_list' %}">
      {% csrf_token %}
      <input type="hidden" name="user_id" value="{{ user.id }}">
      <button class="btn btn-primary" type="submit">
        {% if user.is_blocked %}
          Разблокировать
        {% else %}
          Заблокировать
        {% endif %}
      </button>
    </form>
  </div>
{% endfor %}
{% if not user %}
<p>Пользователей нет.</p>
{% endif %}
{% endblock %}