blog/urls.py
from django.urls import path

from blog.views import BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blogpost/view/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blogpost/<int:pk>/edit/', BlogPostUpdateView.as_view(), name='blogpost_edit'),
    path('blogpost/<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
    path('blogpost/create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blogpost/view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Категория')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    objects = models.Manager()

    def __str__(self):
        return f'{self.name}: {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class BlogPost(models.Model):
    objects = models.Manager()
    title = models.CharField(max_length=300, verbose_name='Заголовок')
    slug = models.CharField(max_length=300, verbose_name='Slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog_previews/', verbose_name='Превью', **NULLABLE)
    created_date = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(default=True)
    views_count = models.IntegerField(default=0)
    category = models.ManyToManyField(Category, verbose_name='Категория')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='владелец')

    def __str__(self):
        return f'{self.title}: {self.content}'

    class Meta:
        verbose_name = 'Запись блога'
        verbose_name_plural = 'Записи блога'
        ordering = ['-created_date']

blog/forms.py
from crispy_forms.helper import FormHelper
from django import forms

from blog.models import BlogPost


class BlogPostForm(forms.ModelForm):
    preview = forms.ImageField(label='Загрузить изображение')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'

    class Meta:
        model = BlogPost
        fields = ['title', 'content', 'preview']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.forms import BlogPostForm
from blog.models import BlogPost, Category


class CategoryBlogView(ListView):
    model = BlogPost
    template_name = 'blog/category_blog.html'
    context_object_name = 'category_blog_list'

    def get_queryset(self):
        category_id = self.kwargs['category_id']
        category = get_object_or_404(Category, id=category_id)
        queryset = BlogPost.objects.filter(category=category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category_id = self.kwargs['category_id']
        category = get_object_or_404(Category, id=category_id)
        context['category'] = category
        return context


class BlogPostListView(ListView):
    model = BlogPost
    template_name = 'blog/blogpost_list.html'
    context_object_name = 'blogposts'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)

        return queryset


class BlogPostCreateView(CreateView):
    model = BlogPost
    template_name = 'blog/create_blog_post.html'
    form_class = BlogPostForm

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        form.instance.is_published = True
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:blogpost_list')


class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/blogpost_details.html'
    context_object_name = 'blogposts'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogPostUpdateView(UpdateView):
    model = BlogPost
    template_name = 'blog/create_blog_post.html'
    form_class = BlogPostForm

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blogpost_view', args=[self.kwargs.get('pk')])


class BlogPostDeleteView(DeleteView):
    model = BlogPost

    def get_success_url(self):
        return reverse_lazy('blog:blogpost_list')

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Подтвердите удаление отзыва "{{ blogpost.title }}"</p>
                            <button type="submit" class="btn btn-dark">Подтвердить</button>
                            <a href="{% url 'catalog:blogpost_list' %}" class="btn btn-info">Отменить</a>

                        </form>


                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/blog/blogpost_details.html
{% extends 'mailing/base.html' %}
{% load my_tags %}

{% load static %}
{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ blogposts.title }}</h2>
            <div class="card-footer">
                Автор: {{ object.owner }}</div><br>
            <p class="card-text"><strong>Контент:</strong><br>{{ blogposts.content }}</p>
            <img src="{{ blogposts.preview|mymedia }}" alt="Изображение" class="card-img-right img-fluid" style="max-width: 600px;"><br>
            <div class="card-footer">
                Просмотры: {{ object.views_count }}</div><br>
             {% if blogpost.owner == request.user %}
            <a href="{% url 'blog:blogpost_edit' blogposts.id %}" class="btn btn-primary">Редактировать</a>
                {% endif %}
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'mailing/base.html' %}
<html lang="ru">
<body>
{% block content %}
{% for blogpost in blogposts %}
<h2>{{ blogpost.title }}</h2>
<p>{{ blogpost.content }}</p>
<a href="{% url 'blog:blogpost_view' blogpost.id %}" class="btn btn-primary">Подробнее</a>

{% if blogpost.owner == request.user %}
<a href="{% url 'blog:blogpost_edit' blogpost.id %}" class="btn btn-info">Редактировать</a>
<a href="{% url 'blog:blogpost_delete' blogpost.id %}" class="btn btn-dark">Удалить</a>
{% endif %}

{% if not blogpost %}
<p>Постов нет, станьте первым.</p>
{% endif %}


{% endfor %}
{% endblock %}

blog/templates/blog/category_blog_list.html
{% extends 'mailing/base.html' %}
{% block content %}
{% for blogpost in category_blog_list %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">{{ blogpost.name }}</h2>
            <p class="card-text">Цена: {{ blogpost.price }}</p>
            <p class="card-text">Описание: {{ blogpost.description }}</p>
            <p class="card-text">Категория: <a href="{% url 'catalog:category_products' category_id=category.id %}">{{ category.name }}</a></p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

blog/templates/blog/create_blog_post.html
{% extends 'mailing/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit">
                                {% if blogpost %}
                                Сохранить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                            <span>{{ form.errors }}</span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}