blog/urls.py
from django.urls import path

from blog.views import BlogPostListView, BlogPostCreateView, BlogPostDetailView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('blogpost/view/', BlogPostListView.as_view(), name='blogpost_list'),
    path('blogpost/<int:pk>/edit/', BlogPostUpdateView.as_view(), name='blogpost_edit'),
    path('blogpost/<int:pk>/delete/', BlogPostDeleteView.as_view(), name='blogpost_delete'),
    path('blogpost/create/', BlogPostCreateView.as_view(), name='blogpost_create'),
    path('blogpost/view/<int:pk>/', BlogPostDetailView.as_view(), name='blogpost_view'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailing.urls', namespace='mailing')),
                  path('users/', include('users.urls', namespace='users')),
                  path('blog/', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, ConfirmEmailView, ConfirmationSuccessView, \
    ConfirmationErrorView, CreationErrorView, ChangePasswordView, GenerateAndSendPasswordView, LoginUserView

app_name = UsersConfig.name
urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login_in'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users/verify_email/', VerifyEmailView.as_view(), name='verification_email'),
    path('confirm_email/<str:token>/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('error_create/', CreationErrorView.as_view(), name='error_create'),
    path('confirmation_success/', ConfirmationSuccessView.as_view(), name='confirmation_success'),
    path('confirmation_error/', ConfirmationErrorView.as_view(), name='confirmation_error'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('generate_send_password/', GenerateAndSendPasswordView.as_view(), name='generate_send_password'),

]

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager, Group, Permission
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=35, verbose_name='Телефон', blank=True, null=True)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', blank=True, null=True)
    country = models.CharField(max_length=50, verbose_name='Страна')
    verification_token = models.CharField(max_length=15, verbose_name='Код верификации', blank=True, null=True)
    is_verified = models.BooleanField(default=False, verbose_name='Статус верификации')
    is_blocked = models.BooleanField(default=False, verbose_name='Статус блокировки')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        permissions = [('can_set_user_blocked', 'Can block user'),
                       ('can_view_users', 'Can view users'),
                       ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))

users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordChangeView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView, LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView
from users.forms import UserRegisterForm, UserProfileForm
from users.services import send_verification_email, send_password


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        verification_token = get_random_string(length=15)
        form.instance.verification_token = verification_token
        send_verification_email(form.instance.email, verification_token)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('users:verification_email')


class LoginUserView(LoginView):
    model = User
    template_name = 'users/login_in.html'

    def get_success_url(self):
        return reverse_lazy('users:profile')


class VerifyEmailView(View):
    template_name = 'users/verification_email.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        verification_code = request.POST.get('verification_code')
        User = get_user_model()
        try:
            user = User.objects.get(verification_token=verification_code)
            if not user.is_verified:
                user.is_verified = True
                user.save()
                return redirect('users:confirmation_success')
        except User.DoesNotExist:
            pass
        return redirect('users:confirmation_error')


class ConfirmationSuccessView(TemplateView):
    template_name = 'users/confirmation_success.html'


class ConfirmationErrorView(TemplateView):
    template_name = 'users/confirmation_error.html'


class CreationErrorView(TemplateView):
    template_name = 'users/password_reset_success.html'


class ConfirmEmailView(View):

    def get(self, request, token):
        User = get_user_model()

        try:
            user = User.objects.get(verification_token=token)
            if not user.is_verified:
                user.is_verified = True
                user.save()
                return render(request, 'confirmation_success.html')

        except User.DoesNotExist:
            return render(request, 'confirmation_error.html')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    form_class = PasswordChangeForm
    success_url = '/users/profile/'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        user = form.save()
        messages.success(self.request, 'Ваш пароль успешно изменен.')
        return super().form_valid(form)


class GenerateAndSendPasswordView(View):
    template_name = 'users/generate_and_send_password.html'
    form = PasswordResetForm()

    def get(self, request):
        return render(request, self.template_name, {'form': self.form})

    def post(self, request):
        self.form = PasswordResetForm(request.POST)
        if self.form.is_valid():
            email = self.form.cleaned_data['email']
            if send_password(email):
                return render(request, 'users/password_reset_success.html', {'email': email})
        return render(request, 'users/password_reset_error.html')

users/templates/users/change_password.html
{% extends 'mailing/base.html' %}
{% block content %}
<h1>Изменить пароль</h1>
<div class="col-12">
    <form method="post" action="{% url 'users:change_password' %}">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                {% csrf_token %}
                {{ form.as_p }}
                <p><input type="submit" class="btn btn-success" value="Изменить"></p>
            </div>
        </div>
    </form>
    </div>
{% endblock %}

users/templates/users/confirmation_error.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 mx-auto text-center">
            <div class="alert alert-danger">
                <h3 class="alert-heading">Ошибка верификации</h3>
                <p>Произошла ошибка при верификации вашей почты. Пожалуйста, проверьте код верификации и попробуйте еще
                    раз.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/confirmation_success.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6 mx-auto text-center">
            <div class="alert alert-success">
                <h3 class="alert-heading">Почта успешно подтверждена!</h3>
                <p>Ваша почта была успешно подтверждена. Теперь вы можете войти на сайт.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/generate_and_send_password.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h2>Восстановление пароля</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.email.label_tag }}
                {{ form.email }}
                <button type="submit" class="btn btn-success" style="margin-top: 15px;">Отправить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="login-form">
                    {% csrf_token %}
                    {{form.as_p }}
                    <input type="hidden" name="next" value="{{ next }}"/>
                    <button type="submit" class="btn btn-success"> Войти</button>
                </div>
            </div>
        </div>
    </form>
    <p>
<a href='{% url "users:generate_send_password" %}'>
Забыли пароль?
</a>
</p>
</div>
{% endblock %}

users/templates/users/login_in.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
                <div class="login-form">
                    {% csrf_token %}
                    {{form.as_p }}
                    <input type="hidden" name="next" value="{{ next }}"/>
                    <button type="submit" class="btn btn-success"> Войти</button>
                </div>
            </div>
        </div>
    </form>
    <p>
<a href='{% url "users:generate_send_password" %}'>
Забыли пароль?
</a>
</p>
</div>
{% endblock %}

users/templates/users/password_reset_error.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="alert alert-danger mt-5">
                <h4 class="alert-heading">Ошибка сброса пароля!</h4>
                <p>Не удалось сбросить пароль для указанного адреса <strong>{{ email }}</strong>. Пожалуйста, убедитесь,
                    что адрес почты корректен и попробуйте снова.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_success.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="alert alert-success mt-5">
                <h4 class="alert-heading">Пароль успешно сброшен!</h4>
                <p>На адрес <strong>{{ email }}</strong> отправлен новый пароль. Пожалуйста, проверьте свою почту и
                    используйте новый пароль для входа.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}


{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{form.as_p }}
                    <button type="submit" class="btn btn-success"> Зарегистрироваться</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Профиль
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{form.as_p }}
                    <button type="submit" class="btn btn-success"> Сохранить</button>
                </div>
            </div>
        </div>
    </form>
        <p>
<a href='{% url "users:change_password" %}'>
Cменить пароль
</a>
</p>
</div>
{% endblock %}

users/templates/users/verification_email.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card mt-5">
                <div class="card-body">
                    <h2 class="card-title">Подтверждение почты</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="verification_code">Введите код верификации:</label>
                            <input type="text" class="form-control" id="verification_code" name="verification_code"
                                   required>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Подтвердить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}